### ISSUE TITLE
Tracking issue: discord API integration

### ISSUE THREAD

**Issue by jonastar** [Botloader/botloader#1]
Note: not all of these are going to be added, this is just a working list to help keep tack of everything and i'll be removing things from the list i see as uneeded/unfit

Channels:

 - [x] Delete/Close Channel
 - [x] Edit Channel
 - [x] Get Channel Messages
 - [x] Get Channel Message
 - [x] Create Message
 - [x] Crosspost Message
 - [x] Create Reaction
 - [x] Delete Own Reaction
 - [x] Delete User Reaction
 - [x] Get Reactions
 - [x] Delete All Reactions
 - [x] Delete All Reactions for Emoji
 - [x] Edit Message
 - [x] Delete Message
 - [x] Bulk Delete Messages
 - [x] Edit Channel Permissions
 - [x] Get Channel Invites
 - [x] Create Channel Invite
 - [x] Delete Channel Permission
 - [x] Get Pinned Messages
 - [x] Pin Message
 - [x] Unpin Message
 - [x] Start Thread with Message
 - [x] Start Thread without Message
 - [ ] Join Thread
 - [x] Add Thread Member
 - [ ] Leave Thread
 - [x] Remove Thread Member
 - [ ] Get Thread Member
 - [x] List Thread Members
 - [x] List Active Threads
 - [x] List Public Archived Threads
 - [x] List Private Archived Threads
 - [ ] List Joined Private Archived Threads

Emojis:

 - [x] List Guild Emojis
 - [x] Get Guild Emoji
 - [x] Create Guild Emoji
 - [x] Modify Guild Emoji
 - [x] Delete Guild Emoji

Guild:

 - [x] Get Guild
 - [ ] Get Guild Preview
 - [ ] Modify Guild
 - [ ] Delete Guild
 - [x] Get Guild Channels
 - [x] Create Guild Channel
 - [x] Modify Guild Channel Positions
 - [x] List Active Threads
 - [x] Get Guild Member
 - [ ] List Guild Members
 - [ ] Search Guild Members
 - [x] Modify Guild Member
 - [ ] Modify Current Member
 - [ ] Modify Current User Nick
 - [x] Add Guild Member Role
 - [x] Remove Guild Member Role
 - [x] Remove Guild Member
 - [x] Get Guild Bans
 - [x] Get Guild Ban
 - [x] Create Guild Ban
 - [x] Remove Guild Ban
 - [x] Get Guild Roles
 - [x] Create Guild Role
 - [x] Modify Guild Role Positions
 - [x] Modify Guild Role
 - [x] Delete Guild Role
 - [ ] Get Guild Prune Count
 - [ ] Begin Guild Prune
 - [ ] Get Guild Voice Regions
 - [x] Get Guild Invites
 - [ ] Get Guild Widget
 - [ ] Get Guild Vanity URL
 - [ ] Get Guild Widget Image
 - [ ] Modify Current User Voice State
 - [ ] Modify User Voice State

Events:
 - [ ] List Scheduled Events for Guild
 - [ ] Create Guild Scheduled Event
 - [ ] Get Guild Scheduled Event
 - [ ] Modify Guild Scheduled Event
 - [ ] Delete Guild Scheduled Event
 - [ ] Get Guild Scheduled Event Users

Misc: 

 - [ ] Get Guild Audit Log
 - [x] Get Invite
 - [x] Delete Invite

Stage channels:

 - [ ] Create Stage Instance
 - [ ] Get Stage Instance
 - [ ] Modify Stage Instance
 - [ ] Delete Stage Instance

Stickers:

 - [ ] Get Sticker
 - [ ] List Nitro Sticker Packs
 - [ ] List Guild Stickers
 - [ ] Get Guild Sticker
 - [ ] Create Guild Sticker
 - [ ] Modify Guild Sticker
 - [ ] Delete Guild Sticker

Webhooks:

 - [x] Get Channel Webhooks
 - [x] Get Guild Webhooks
 - [x] Get Webhook
 - [x] Get Webhook with Token
 - [x] Modify Webhook
 - [x] Modify Webhook with Token
 - [x] Delete Webhook
 - [x] Delete Webhook with Token
 - [x] Execute Webhook
 - [x] Get Webhook Message
 - [x] Edit Webhook Message
 - [x] Delete Webhook Message
