### ISSUE TITLE
Tracking issue: discord API integration

### ISSUE THREAD

**Issue by jonas747** [Botloader/botloader#31]
Note: not all of these are going to be added, this is just a working list to help keep tack of everything and i'll be removing things from the list i see as uneeded/unfit

Channels:

 - [ ] Delete/Close Channel
 - [ ] Get Channel Messages
 - [ ] Get Channel Message
 - [ ] Create Message
 - [ ] Crosspost Message
 - [ ] Create Reaction
 - [ ] Delete Own Reaction
 - [ ] Delete User Reaction
 - [ ] Get Reactions
 - [ ] Delete All Reactions
 - [ ] Delete All Reactions for Emoji
 - [ ] Edit Message
 - [ ] Delete Message
 - [ ] Bulk Delete Messages
 - [ ] Edit Channel Permissions
 - [ ] Get Channel Invites
 - [ ] Create Channel Invite
 - [ ] Delete Channel Permission
 - [ ] Get Pinned Messages
 - [ ] Pin Message
 - [ ] Unpin Message
 - [ ] Start Thread with Message
 - [ ] Start Thread without Message
 - [ ] Join Thread
 - [ ] Add Thread Member
 - [ ] Leave Thread
 - [ ] Remove Thread Member
 - [ ] Get Thread Member
 - [ ] List Thread Members
 - [ ] List Active Threads
 - [ ] List Public Archived Threads
 - [ ] List Private Archived Threads
 - [ ] List Joined Private Archived Threads

Emojis:

 - [ ] List Guild Emojis
 - [ ] Get Guild Emoji
 - [ ] Create Guild Emoji
 - [ ] Modify Guild Emoji
 - [ ] Delete Guild Emoji

Guild:

 - [ ] Get Guild
 - [ ] Get Guild Preview
 - [ ] Modify Guild
 - [ ] Delete Guild
 - [ ] Get Guild Channels
 - [ ] Create Guild Channel
 - [ ] Modify Guild Channel Positions
 - [ ] List Active Threads
 - [ ] Get Guild Member
 - [ ] List Guild Members
 - [ ] Search Guild Members
 - [ ] Add Guild Member
 - [ ] Modify Guild Member
 - [ ] Modify Current Member
 - [ ] Modify Current User Nick
 - [ ] Add Guild Member Role
 - [ ] Remove Guild Member Role
 - [ ] Remove Guild Member
 - [ ] Get Guild Bans
 - [ ] Get Guild Ban
 - [ ] Create Guild Ban
 - [ ] Remove Guild Ban
 - [ ] Get Guild Roles
 - [ ] Create Guild Role
 - [ ] Modify Guild Role Positions
 - [ ] Modify Guild Role
 - [ ] Delete Guild Role
 - [ ] Get Guild Prune Count
 - [ ] Begin Guild Prune
 - [ ] Get Guild Voice Regions
 - [ ] Get Guild Invites
 - [ ] Get Guild Widget
 - [ ] Get Guild Vanity URL
 - [ ] Get Guild Widget Image
 - [ ] Modify Current User Voice State
 - [ ] Modify User Voice State

Events:
 - [ ] List Scheduled Events for Guild
 - [ ] Create Guild Scheduled Event
 - [ ] Get Guild Scheduled Event
 - [ ] Modify Guild Scheduled Event
 - [ ] Delete Guild Scheduled Event
 - [ ] Get Guild Scheduled Event Users

Misc: 

 - [ ] Get Guild Audit Log
 - [ ] Get Invite
 - [ ] Delete Invite

Stage channels:

 - [ ] Create Stage Instance
 - [ ] Get Stage Instance
 - [ ] Modify Stage Instance
 - [ ] Delete Stage Instance

Stickers:

Get Sticker
 - [ ] List Nitro Sticker Packs
 - [ ] List Guild Stickers
 - [ ] Get Guild Sticker
 - [ ] Create Guild Sticker
 - [ ] Modify Guild Sticker
 - [ ] Delete Guild Sticker

Webhooks:

Don't think i'll add any webhook endpoints, we'll see in the future
